title = "Dylan Barker"
baseURL = "https://dylantjb.com"
languageCode = "en-gb"
theme = "ananke"
themesDir = "themes"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[taxonomies]
  tag = "tags"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"



[params]
  favicon = "/images/favicon.ico"
  site_logo = "/images/developer.ico"
  body_classes = "avenir bg-light-gray"
  images = ["/images/social-media.png"]
  description = ""
  facebook = ""
  twitter = "https://twitter.com/dylantjb"
  instagram = ""
  youtube = ""
  github = "https://github.com/dylantjb"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/dylantjb"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  featured_image = "/images/home-background.jpg"
  recent_posts_number = 2
