title = "Dylan Barker"
baseURL = "https://dylantjb.com"
languageCode = "en-gb"
theme = "ananke"
themesDir = "themes"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  site_logo = "/images/developer.ico"
  body_classes = "serif bg-light-gray"
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/dylan9012"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/dylantjb"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  featured_image = "/images/home-background.jpg"
  recent_posts_number = 2



# TODO: Optimise website images
#       